# Generated by Django 5.2.8 on 2025-11-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/'),
        ),
    ]
