# Generated by Django 5.2.8 on 2025-11-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('gambar', models.ImageField(upload_to='gallery/')),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
