# Generated by Django 5.2.8 on 2025-11-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
