# Generated by Django 5.2.8 on 2025-11-07 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_staff_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
